debug line test

diff --git a/chdir b/chdir
--- a/chdir
+++ b/chdir
@@ -15,15 +15,15 @@ elif [[ -d ".$1" ]]; then       #if the a hidden directory matches the argument,
 elif [[ "$1" == '-' ]]; then    #if we passed '-' as the argument, then
     new_dir="-"                 #act like cd
 else
-    error_msg="directory \`$red$bold$1$reset' not found."    #say we cant find it
+	error_msg="$(realpath $0): directory \`$red$bold$1$reset' not found."    #say we cant find it
 fi
 
-if [[ -n "$error_msg" ]]; then     #if there was an error message, then
-    echo "chdir: $error_msg" 1>&2  #tell me what it was
-    unset error_msg                #and unset this for no reason :V
+if [[ -n "$error_msg" ]]; then              #if there was an error message, then
+    echo "$(realpath $0): $error_msg" 1>&2  #tell me what it was
+    unset error_msg           	            #and unset this for no reason :V
 else
     builtin cd "$new_dir"
-    timeout 1 ls --color=auto --format=across --group-directories-first || echo "chdir: Timeout listing directory contents."
+    timeout 1 ls --color=auto --format=across --group-directories-first || echo "$(realpath $0): Timeout listing directory contents."
 fi
 
 }
diff --git a/extract b/extract
--- a/extract
+++ b/extract
@@ -1,14 +1,14 @@
 #!/usr/bin/bash
 #
-# decompress archives
+# decompress archives based on mimetype
 #
 
 if [[ -f "$1" ]] ; then
       
     #get the mime type
-    mime=$(file -Lb --mime-type "$1")
+    mime="$(file -Lb --mime-type $1)"
     
-    case ${mime#*-} in
+    case "${mime#*-}" in
         bzip2)
             cmd=(bunzip2 "$1")
             ;;
@@ -59,14 +59,14 @@ if [[ -f "$1" ]] ; then
     esac
     
     #Check for missing dependency
-    [[ "$dep" ]] && type -P "$dep" > /dev/null || { echo "extract: Missing dependency: $dep"; exit 1; }
+    [[ "$dep" ]] && type -P "$dep" > /dev/null || { echo "$(realpath $0): Missing dependency: $dep"; exit 1; }
     
     #Run the extraction command
     "${cmd[@]}"
     
-    [[ -e "$1" ]] || echo "extract: WARNING! $1 was removed after extracting."
+    [[ -e "$1" ]] || echo "$(realpath $0): WARNING! $1 was removed after extracting."
     
 else
-    echo "extract: $1 is not a valid file"
+	echo "$(realpath $0): $1 is not a valid file"
     exit 1
 fi
