better folding

diff --git a/chdir b/chdir
--- a/chdir
+++ b/chdir
@@ -7,16 +7,17 @@
 # README file for terms and conditions on your use of this software.
 #
 
-#
+# Function {{{0
+ch() {
 # Usage {{{1
 #
 usage() {
 cat <<EOD
-chdir
+ch
 © Copyright 2014 Ryan Delaney. All rights reserved.
 Web site: http://github.com/rpdelaney
 
-chdir provides enhanced directory changing behavior.
+ch provides enhanced directory changing behavior.
 
 Usage: chdir [PATH]
 
@@ -27,8 +28,7 @@ EOD
 exit 1
 }
 
-#
-# Shell arguments {{{1
+# Parameters {{{1
 #
 while :
 do
@@ -58,35 +58,28 @@ do
 done
 
 # Action {{{1
-#
 
-#script=`realpath $0`
-#scriptPath=`dirname $script`
-scriptPath="chdir"
+  if [[ ! "$1" ]]; then           # if there's no argument
+      new_dir=""                  # stay put
+  elif [[ -d "$1" ]]; then        # if the argument is an existing directory, then
+      new_dir="$1"                # set new_dir to that path
+  elif [[ -d ".$1" ]]; then       # if the a hidden directory matches the argument, then
+      new_dir=".$1"               # set new_dir to the hidden path
+  elif [[ "$1" == '-' ]]; then    # if we passed '-' as the argument, then
+      new_dir="-"                 # act like cd
+  else
+      error_msg="directory \`$red$bold$1$reset' not found."    #say we cant find it
+  fi
 
-ch() {
-if [[ ! "$1" ]]; then           # if there's no argument
-    new_dir=""                  # stay put
-elif [[ -d "$1" ]]; then        # if the argument is an existing directory, then
-    new_dir="$1"                # set new_dir to that path
-elif [[ -d ".$1" ]]; then       # if the a hidden directory matches the argument, then
-    new_dir=".$1"               # set new_dir to the hidden path
-elif [[ "$1" == '-' ]]; then    # if we passed '-' as the argument, then
-    new_dir="-"                 # act like cd
-else
-    error_msg="directory \`$red$bold$1$reset' not found."    #say we cant find it
-fi
-
-if [[ -n "$error_msg" ]]; then                  # if there was an error message, then
-    echo "$scriptPath: $error_msg" 1>&2         # tell me what it was
-    unset error_msg                             # and unset this for no reason :V
-else
-    builtin cd "$new_dir"
-    timeout 1 ls --color=auto --format=across --group-directories-first || echo "$scriptPath: Timeout listing directory contents."
-fi
-
+  if [[ -n "$error_msg" ]]; then                  # if there was an error message, then
+      echo "chdir: $error_msg" 1>&2               # tell me what it was
+      unset error_msg                             # and unset this for no reason :V
+  else
+      builtin cd "$new_dir"
+      timeout 1 ls --color=auto --format=across --group-directories-first || echo "$scriptPath: Timeout listing directory contents."
+  fi
 }
 
 # Modelines {{{1
 #
-# vim: ft=sh foldmethod=marker
+# vim: ft=sh foldmethod=marker foldlevel=0
