(\ /) (O.o) (> <) Bunny approves these changes.

diff --git a/chdir b/chdir
--- a/chdir
+++ b/chdir
@@ -3,20 +3,28 @@
 #augmented 'cd'
 #provides enhanced directory changing behavior
 #
-if [ -d "$@" ]; then            #if the argument is an existing directory, then
-    new_dir="$@"                #set new_dir to that path
-elif [ -d ."$@" ]; then         #if the a hidden directory matches the argument, then
-    new_dir=".""$@"             #set new_dir to the hidden path
-elif [ "$@" == '-' ]; then      #if we passed '-' as the argument, then
+
+ch() {
+
+if [[ ! "$1" ]]; then           #if there's no argument
+    new_dir=""                  #stay put
+elif [[ -d "$1" ]]; then        #if the argument is an existing directory, then
+    new_dir="$1"                #set new_dir to that path
+elif [[ -d ."$1" ]]; then       #if the a hidden directory matches the argument, then
+    new_dir=".""$1"             #set new_dir to the hidden path
+elif [[ "$1" == '-' ]]; then    #if we passed '-' as the argument, then
     new_dir="-"                 #act like cd
-else                            #otherwise
-    error_msg="cd: directory "$red$bold$1$reset" not found."    #say we can't find it
+else
+    error_msg="cd: directory $red$bold$1$reset not found."    #say we can't find it
 fi
 
-if [ "$error_msg" ]; then       #if there was an error message, then
-    echo "$error_msg"
-    unset error_msg
+if [[ -n "$error_msg" ]]; then     #if there was an error message, then
+    echo "chdir: $error_msg" 1>&2  #tell me what it was
+    unset error_msg                #and unset this for no reason :V
+    exit 1
 else
     builtin cd "$new_dir"
-    timeout 3 /usr/bin/ls --color=always --format=across --group-directories-first || echo "Timeout listing directory contents."
+    timeout 1 ls --color=always --format=across --group-directories-first || echo "chdir: Timeout listing directory contents."
 fi
+
+}
