Major revision - Replaced clumsy error handling. - Added support for recursive searching when the target is not a directory - Better validation of user input - Delineated work units into separate functions. - Unset the helper functions when exiting.

diff --git a/chdir b/chdir
--- a/chdir
+++ b/chdir
@@ -44,6 +44,7 @@ Usage: chdir [PATH]
 Options
   -?, --help                  print this help and return
   -v, --verbose               increase verbosity
+  -s, --strict                don't recursively search for a suitable path
   -u, --up=N                  move up N directories
 EOD
 return 1
@@ -89,37 +90,55 @@ if [[ -z "$1" ]]; then
   return 1
 fi
 # }}}
-# Action {{{1
+finddir() { # {{{1
+  new_dir="$1"
 
-  # If -u argument was passed, move up N directories.
-if [[ -z "$moveup" ]]; then
-  if [[ -d "$1" ]]; then          # if the argument is an existing directory, then
-      new_dir="$1"                # set new_dir to that path
-  elif [[ -d ".$1" ]]; then       # if the a hidden directory matches the argument, then
-      new_dir=".$1"               # set new_dir to the hidden path
-  elif [[ -d "$(dirname "$1")" ]]; then # if the directory under it exists, then
-      new_dir="$(dirname "$1")"   # go there
-  elif [[ "$1" == '-' ]]; then    # if we passed '-' as the argument, then
-      new_dir="-"                 # act like cd
-  else
-      error_msg="directory \`$red$bold$1$reset' not found."    #say we cant find it
+  if [[ "$new_dir" == '-' ]]; then
+    return 0
   fi
-else
-  for i in seq 1 "$moveup"; do
-    cd ..
+
+  while [[ -z "$norecurse" ]]; do
+    if [[ "$new_dir" == "$PWD" ]] || [[ "$new_dir" == "/" ]]; then
+      error "Hit the ceiling at $new_dir"
+      return 0
+    elif [[ -d "$new_dir" ]]; then
+      return 0
+    elif [[ -d ".$new_dir" ]]; then
+      new_dir=".$new_dir"
+      return 0
+    else
+      error "No suitable target found at $new_dir"
+      error " Recursing up the directory tree..."
+      new_dir="$(dirname "$new_dir")"
+    fi
   done
-fi
 
-
-if [[ -n "$error_msg" ]]; then                  # if there was an error message, then
-    echo "chdir: $error_msg" 1>&2               # tell me what it was
-    unset error_msg                             # and unset this for no reason :V
+if [[ -d "$new_dir" ]]; then
+  return 0
 else
-    builtin cd "$new_dir"
-    timeout 1 ls --color=auto --format=across --group-directories-first || echo "$scriptPath: Timeout listing directory contents."
+  return 1
 fi
+} # 1}}}
+moveupdir() { # {{{1
+    for i in seq 1 "$moveup"; do
+      cd .. || return 1
+    done
+    return 0
+} # }}}
+
+if [[ -n "$moveup" ]]; then
+  # If -u argument was passed, move up N directories.
+  moveupdir "$1"
+  return 0
+fi
+if finddir "$1"; then
+  builtin cd "$new_dir" && { timeout 1 ls --color=auto --format=across --group-directories-first || echo "$scriptPath: Timeout listing directory contents." ; }
+else
+  error "FATAL: Directory not found."
+fi
+
+unset usage
+unset finddir 
+
 }
-
-# }}}
-
 # vim: ft=sh foldmethod=marker foldlevel=0
