renamed fdupes to fdup to avoid collisions

diff --git a/fdup b/fdup
--- a/fdup
+++ b/fdup
@@ -7,8 +7,7 @@
 # See the README file for additional terms and conditions on your use of this
 # software.
 #
-# TODO: Find Duplicate Files (based on size first, then MD5 hash)
-# find -not -empty -type f -printf "%s\n" | sort -rn | uniq -d | xargs -I{} -n1 find -type f -size {}c -print0 | xargs -0 md5sum | sort | uniq -w32 --all-repeated=separate
+# TODO: Find Duplicate Files (based on size first, then CRC hash)
 #
 # Functions {{{1
 verbose() {
@@ -17,8 +16,12 @@ verbose() {
   fi
 }
 
-error () {
+error() {
   echo "$1" >&2
+}
+
+inodes() {
+  [[ -f "$1" ]] && stat --format='%i %h %n' "$1" || error "WARNNING: File not found: $1"
 }
 # }}}
 # Usage {{{1
@@ -77,16 +80,27 @@ done
 haystack="$1"
 # }}}
 # Dependencies {{{1
-if ! type md5sum &> /dev/null; then
-  error "FATAL: missing dependency: md5sum" && exit 1
-fi
-
-if [[ ! -d "$haystack" ]]; then
-  error "FATAL: directory not found: $haystack" && exit 1
-fi
+if [[ ! -d "$haystack" ]]; then error "FATAL: directory not found: $haystack" && exit 1; fi
+if ! type md5sum &> /dev/null; then error "FATAL: missing dependency: md5sum" && exit 1; fi
+if ! type find &> /dev/null; then echo "ERROR: Missing dependency: find" 1>&2; exit 1; fi
+if ! type stat &> /dev/null; then echo "ERROR: Missing dependency: stat" 1>&2; exit 1; fi
 # }}}
 # Work {{{1
 cd "$haystack"
-find -L -type f -exec md5sum '{}' ';' | sort | uniq --all-repeated=separate -w 33 | cut -c 35-
+
+# Perform file size comparison {{{2
+# Files that do not have matching file sizes are not duplicates
+while read file; do
+  stat --format="%s##%n" "$file"
+done < <(find . -type f) | sort -g
+exit 0
 # }}}
+[[ ! -f fdupes.crc ]] && cfv -rr -t crc -f fdupes.crc -C # || { error "FATAL: fdupes: CRC checking failed." ; exit 1 ; }
+
+dupes="$(grep -Po '[a-z0-9]{8}[ ]*$' fdupes.crc | awk 'seen[$0]++')"
+
+for crc in $dupes; do grep "$crc" fdupes.crc && echo "--"; done
+
+# }}}
+
 # vim: ft=sh foldmethod=marker:
