Print a warning if we aren't doing anything

diff --git a/path b/path
--- a/path
+++ b/path
@@ -163,6 +163,10 @@ do
       shift
       ;;
     *)  # no more options. Stop while loop
+      if [[ -z "${append[*]}" && -z "${prepend[*]}" && -z "${delete[*]}" ]] ; then
+        echo "WARN: Missing command (need one of '-a', '-p', or '-d')" 1>&2
+        exit 1
+      fi
       break
       ;;
   esac
