Use psgrep in psx for compatibility. Fixes #2

diff --git a/psx b/psx
--- a/psx
+++ b/psx
@@ -76,12 +76,12 @@ exit 1
 # Usage 1}}}
 
 # Validation {{{1
-if ! type pgrep &> /dev/null; then echo "ERROR: Missing dependency: pgrep" 1>&2; exit 1; fi
+if ! type psgrep &> /dev/null; then echo "ERROR: Missing dependency: psgrep" 1>&2; exit 1; fi
 if ! type mktemp &> /dev/null; then echo "Missing dependency: mktemp" 1>&2; exit 1; fi
 # 1}}}
 
 word="$*"
-pids="$(pgrep "$word")"
+pids="$(psgrep -d "$word")"
 
 if [[ -n "$pids" ]]; then
   if [[ -z "$verbose" ]]; then
@@ -96,7 +96,7 @@ if [[ -n "$pids" ]]; then
       while read line; do
         echo "$line" >> "$tmpfile"
       done
-    } < <( ps u --sort=uid,pid -p $pids )
+    } < <( psgrep $pids )
 
     cols=${COLUMNS:="$(tput cols)"}
 
